// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p19
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// C:\Users\Corey\Desktop\OpenDDS-3.16\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:376


#include "FlamingoTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "FlamingoTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// C:\Users\Corey\Desktop\OpenDDS-3.16\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for src::FlamingoTypeSupport.

src::FlamingoTypeSupport_ptr
TAO::Objref_Traits<src::FlamingoTypeSupport>::duplicate (
    src::FlamingoTypeSupport_ptr p)
{
  return src::FlamingoTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<src::FlamingoTypeSupport>::release (
    src::FlamingoTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

src::FlamingoTypeSupport_ptr
TAO::Objref_Traits<src::FlamingoTypeSupport>::nil (void)
{
  return src::FlamingoTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<src::FlamingoTypeSupport>::marshal (
    const src::FlamingoTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

src::FlamingoTypeSupport::FlamingoTypeSupport (void)
{}

src::FlamingoTypeSupport::~FlamingoTypeSupport (void)
{
}

src::FlamingoTypeSupport_ptr
src::FlamingoTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return FlamingoTypeSupport::_duplicate (
      dynamic_cast<FlamingoTypeSupport_ptr> (_tao_objref)
    );
}

src::FlamingoTypeSupport_ptr
src::FlamingoTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return FlamingoTypeSupport::_duplicate (
      dynamic_cast<FlamingoTypeSupport_ptr> (_tao_objref)
    );
}

src::FlamingoTypeSupport_ptr
src::FlamingoTypeSupport::_nil (void)
{
  return 0;
}

src::FlamingoTypeSupport_ptr
src::FlamingoTypeSupport::_duplicate (FlamingoTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
src::FlamingoTypeSupport::_tao_release (FlamingoTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
src::FlamingoTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:src/FlamingoTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* src::FlamingoTypeSupport::_interface_repository_id (void) const
{
  return "IDL:src/FlamingoTypeSupport:1.0";
}

::CORBA::Boolean
src::FlamingoTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// C:\Users\Corey\Desktop\OpenDDS-3.16\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for src::FlamingoDataWriter.

src::FlamingoDataWriter_ptr
TAO::Objref_Traits<src::FlamingoDataWriter>::duplicate (
    src::FlamingoDataWriter_ptr p)
{
  return src::FlamingoDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<src::FlamingoDataWriter>::release (
    src::FlamingoDataWriter_ptr p)
{
  ::CORBA::release (p);
}

src::FlamingoDataWriter_ptr
TAO::Objref_Traits<src::FlamingoDataWriter>::nil (void)
{
  return src::FlamingoDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<src::FlamingoDataWriter>::marshal (
    const src::FlamingoDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

src::FlamingoDataWriter::FlamingoDataWriter (void)
{}

src::FlamingoDataWriter::~FlamingoDataWriter (void)
{
}

src::FlamingoDataWriter_ptr
src::FlamingoDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return FlamingoDataWriter::_duplicate (
      dynamic_cast<FlamingoDataWriter_ptr> (_tao_objref)
    );
}

src::FlamingoDataWriter_ptr
src::FlamingoDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return FlamingoDataWriter::_duplicate (
      dynamic_cast<FlamingoDataWriter_ptr> (_tao_objref)
    );
}

src::FlamingoDataWriter_ptr
src::FlamingoDataWriter::_nil (void)
{
  return 0;
}

src::FlamingoDataWriter_ptr
src::FlamingoDataWriter::_duplicate (FlamingoDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
src::FlamingoDataWriter::_tao_release (FlamingoDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
src::FlamingoDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:src/FlamingoDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* src::FlamingoDataWriter::_interface_repository_id (void) const
{
  return "IDL:src/FlamingoDataWriter:1.0";
}

::CORBA::Boolean
src::FlamingoDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// C:\Users\Corey\Desktop\OpenDDS-3.16\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for src::FlamingoDataReader.

src::FlamingoDataReader_ptr
TAO::Objref_Traits<src::FlamingoDataReader>::duplicate (
    src::FlamingoDataReader_ptr p)
{
  return src::FlamingoDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<src::FlamingoDataReader>::release (
    src::FlamingoDataReader_ptr p)
{
  ::CORBA::release (p);
}

src::FlamingoDataReader_ptr
TAO::Objref_Traits<src::FlamingoDataReader>::nil (void)
{
  return src::FlamingoDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<src::FlamingoDataReader>::marshal (
    const src::FlamingoDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

src::FlamingoDataReader::FlamingoDataReader (void)
{}

src::FlamingoDataReader::~FlamingoDataReader (void)
{
}

src::FlamingoDataReader_ptr
src::FlamingoDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return FlamingoDataReader::_duplicate (
      dynamic_cast<FlamingoDataReader_ptr> (_tao_objref)
    );
}

src::FlamingoDataReader_ptr
src::FlamingoDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return FlamingoDataReader::_duplicate (
      dynamic_cast<FlamingoDataReader_ptr> (_tao_objref)
    );
}

src::FlamingoDataReader_ptr
src::FlamingoDataReader::_nil (void)
{
  return 0;
}

src::FlamingoDataReader_ptr
src::FlamingoDataReader::_duplicate (FlamingoDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
src::FlamingoDataReader::_tao_release (FlamingoDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
src::FlamingoDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:src/FlamingoDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* src::FlamingoDataReader::_interface_repository_id (void) const
{
  return "IDL:src/FlamingoDataReader:1.0";
}

::CORBA::Boolean
src::FlamingoDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

